---
- name: Converge
  hosts: all
  become: true
  vars:
    jenkins_plugins:
      - configuration-as-code
      - configuration-as-code-support

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install dependencies.
      apt:
        default_release: "{{ ansible_distribution_release }}-backports"
        name:
          - openjdk-8-jre-headless
          - ca-certificates-java
        state: present
      when: ansible_distribution == "Debian"

    - name: Set the java_packages variable (Debian).
      set_fact:
        java_packages:
          - openjdk-8-jdk
      when: ansible_distribution == 'Debian'

    - name: Set the java_packages variable (Ubuntu).
      set_fact:
        java_packages:
          - openjdk-8-jdk
      when: ansible_distribution == 'Ubuntu'

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
    - role: mattandes.jenkins_casc

  post_tasks:
    - name: Check if Jenkins is running
      uri:
        url: "http://127.0.0.1:8080/"
        status_code: 200
        return_content: true
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Check if JASC message is present
      assert:
        that: "'Jenkins configured automatically by Jenkins Configuration as Code Plugin' in result.content"
