---
- name: Converge
  hosts: all
  become: true
  vars:
    jenkins_plugins:
      - configuration-as-code
      - configuration-as-code-support

  pre_tasks:
    - include_tasks: java-8.yml

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
    - role: mattandes.jenkins_casc

  post_tasks:
    - name: Check if Jenkins is running
      uri:
        url: "http://127.0.0.1:8080/"
        status_code: 200
        return_content: true
      register: result
      until: result.status == 200
      retries: 60
      delay: 1

    - name: Check if JASC message is present
      assert:
        that: "'Jenkins configured automatically by Jenkins Configuration as Code Plugin' in result.content"
